apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJNREIzZWpwbmFIQmZSVTR3TUVOc1FWaDJSRTkwVG5OeE4zVmFhMWx6T1hoeGEwMDRSV0p6TTFSRGJGVlMiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
